full:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

minimal:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ..
    - make -j 4
    
test:
  tags:
    - windows
  script:
    - md build
    - cd build
    - cmake ..
    - msbuild
    
    