# Gmsh - Copyright (C) 1997-2017 C. Geuzaine, J.-F. Remacle
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to the public mailing list <gmsh@onelab.info>.

variables:
  EXTRA_VERSION: "-git-$CI_COMMIT_SHA"

# -----------------------
# Builds for all branches
# -----------------------

linux64_docker_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} ..
    - make -j 4
    - ctest -j 4 --output-on-failure
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_docker_cxx98_compat_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - export CXXFLAGS=-std=c++98
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DENABLE_CXX11=0 -DENABLE_OCC=0 ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_docker_minimal_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

windows64_msvc_ci:
  script:
    - md build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=%EXTRA_VERSION:~0,13% ..
    - msbuild package.vcxproj
  tags:
    - windows64
    - official
  except:
    - tags

