# Gmsh - Copyright (C) 1997-2018 C. Geuzaine, J.-F. Remacle
#
# See the LICENSE.txt file for license information. Please report all
# bugs and problems to the public mailing list <gmsh@onelab.info>.

variables:
  EXTRA_VERSION: "-git-$CI_COMMIT_SHA"
  EXTRA_OPTION: ""

# -----------------------
# Builds for all branches
# -----------------------

linux64_docker_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} ${EXTRA_OPTION} ..
    - make -j 4
    - ctest -j 4 --output-on-failure
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_docker_cxx98_compat_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - export CXXFLAGS=-std=c++98
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DENABLE_CXX11=0 -DENABLE_OCC=0 ${EXTRA_OPTION} ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

linux64_docker_minimal_ci:
  image: onelab/ubuntu16.04
  script:
    - mkdir build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ${EXTRA_OPTION} ..
    - make -j 4
  tags:
    - linux64
    - docker
  except:
    - tags

windows64_msvc_ci:
  script:
    - md build
    - cd build
    - cmake -DGMSH_EXTRA_VERSION=%EXTRA_VERSION:~0,13% -DENABLE_HXT=0 ${EXTRA_OPTION} ..
    - msbuild package.vcxproj
  tags:
    - windows64
    - official
  except:
    - tags

# ------------------------------------------
# Official Linux builds (master branch only)
# ------------------------------------------

.linux_official: &linux_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local' -DENABLE_NATIVE_FILE_CHOOSER:bool=FALSE -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 ${EXTRA_OPTION} ..
    - make package -j 1
    - PKG=`ls gmsh-*.tar*`
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@gmsh.info:.wwwgmsh/bin/Linux/${PKG/\.tar\.gz/\.tgz}
    - /usr/local/bin/ctest -D Experimental -j 1 --output-on-failure

linux64_official_snapshot:
  <<: *linux_official
  tags:
    - linux64
    - official
  except:
    - tags

linux64_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *linux_official
  tags:
    - linux64
    - official
  only:
    - /^gmsh_.*$/

linux64-dev_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_BUILD_DYNAMIC=1"
  <<: *linux_official
  tags:
    - linux64
    - official
  except:
    - tags

linux32_official_snapshot:
  <<: *linux_official
  tags:
    - linux32
    - official
  except:
    - tags

linux32_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *linux_official
  tags:
    - linux32
    - official
  only:
    - /^gmsh_.*$/

linux32-dev_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_BUILD_DYNAMIC=1"
  <<: *linux_official
  tags:
    - linux32
    - official
  except:
    - tags

# --------------------------------------------
# Official Windows builds (master branch only)
# --------------------------------------------

.windows_official: &windows_official
  only:
    - master@gmsh/gmsh
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 -DENABLE_OS_SPECIFIC_INSTALL=1 ${EXTRA_OPTION} .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa gmsh-*.zip geuzaine@gmsh.info:.wwwgmsh/bin/Windows/"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"

windows64_official_snapshot:
  <<: *windows_official
  tags:
    - windows64
    - official
  except:
    - tags

windows64_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *windows_official
  tags:
    - windows64
    - official
  only:
    - /^gmsh_.*$/

.windows64-dev_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1"
  <<: *windows_official
  tags:
    - windows64
    - official
  except:
    - tags

windows32_official_snapshot:
  <<: *windows_official
  tags:
    - windows32
    - official
  except:
    - tags
  allow_failure: true

windows32_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *windows_official
  tags:
    - windows32
    - official
  only:
    - /^gmsh_.*$/

.windows32-dev_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1"
  <<: *windows_official
  tags:
    - windows32
    - official
  except:
    - tags

# ------------------------------------------
# Official MacOS builds (master branch only)
# ------------------------------------------

.macos_official: &macos_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} -DGMSH_HOST=gmsh.info -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local' -DCMAKE_C_COMPILER=/opt/local/bin/clang-mp-3.9 -DCMAKE_CXX_COMPILER=/opt/local/bin/clang++-mp-3.9 -DENABLE_CAIRO=0 -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/Users/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/Users/geuzaine/src/slepc-3.7.3 -DBLAS_LAPACK_LIBRARIES=/usr/local/lib/libopenblas.a -DENABLE_OS_SPECIFIC_INSTALL=1 ${EXTRA_OPTION} ..
    - make package -j 2
    - PKG=`ls gmsh-*.[dt][ma][gr]*`
    - if [[ $PKG == *".dmg"* ]]; then scp ${PKG} ace@ace36.montefiore.ulg.ac.be:/tmp; fi
    - if [[ $PKG == *".dmg"* ]]; then ssh ace@ace36.montefiore.ulg.ac.be /Users/ace/re-sign.sh /tmp/${PKG}; fi
    - if [[ $PKG == *".dmg"* ]]; then scp ace@ace36.montefiore.ulg.ac.be:/tmp/${PKG} .; fi
    - scp ${PKG} geuzaine@gmsh.info:.wwwgmsh/bin/MacOSX/${PKG/\.tar\.gz/\.tgz}
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure

macos64_official_snapshot:
  <<: *macos_official
  tags:
    - macos64
    - official
  except:
    - tags

macos64_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *macos_official
  tags:
    - macos64
    - official
  only:
    - /^gmsh_.*$/

macos64-dev_official_snapshot:
  variables:
    EXTRA_OPTION: "-DENABLE_OS_SPECIFIC_INSTALL=0 -DENABLE_BUILD_DYNAMIC=1"
  <<: *macos_official
  tags:
    - macos64
    - official
  except:
    - tags

# ----------------------------------------------
# Official source snapshots (master branch only)
# ----------------------------------------------

.source_official: &source_official
  only:
    - master@gmsh/gmsh
  script:
    - mkdir build_src
    - cd build_src
    - /usr/local/bin/cmake -DGMSH_EXTRA_VERSION=${EXTRA_VERSION:0:13} ${EXTRA_OPTION} ..
    - make package_source
    - PKG=`ls gmsh-*.tar*`
    - scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@gmsh.info:.wwwgmsh/src/${PKG/\.tar\.gz/\.tgz}

source_official_snapshot:
  <<: *source_official
  tags:
    - linux64
    - official
  except:
    - tags

source_official_release:
  variables:
    EXTRA_VERSION: ""
  <<: *source_official
  tags:
    - linux64
    - official
  only:
    - /^gmsh_.*$/
