makegmsh:
  image : immc/gmsh:v0.4
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - ctest --output-on-failure

makegmsh-test:
  image : onelab/gmsh
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest --output-on-failure
