linux64_gcc:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

linux64_gcc_minimal:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ..
    - make -j 4
    
windows64_msvc:
  tags:
    - windows
  script:
    - bash -c "echo $PWD; mkdir aaa; cd aaa; /usr/bin/cmake -DCMAKE_PREFIX_PATH:path=/usr/local/opencascade;/usr/local;/usr/x86_64-w64-mingw32/sys-root/mingw -DCMAKE_C_COMPILER=/usr/bin/x86_64-w64-mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/x86_64-w64-mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/x86_64-w64-mingw32-windres.exe -DPETSC_ARCH=win64_complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5-DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 .."
    - md build
    - cd build
    #- cmake ..
    #- msbuild package.vcxproj
    .."
    - bash --login -c "echo $PWD"
    - md build
    - cd build
    #- cmake ..
    #- msbuild package.vcxproj
    
    