linux64_gcc:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

linux64_gcc_minimal:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ..
    - make -j 4
    
windows64_msvc:
  tags:
    - windows
  script:
    - bash -c "echo $PWD; mkdir aaa; cd aaa; cmake .."
    - bash --login -c "echo $PWD"
    - md build
    - cd build
    #- cmake ..
    #- msbuild package.vcxproj
    
    