build_docker_linux_gcc:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - ctest -j 4 --output-on-failure

build_docker_linux_gcc_minimal:
  image: onelab/ubuntu16.04
  tags:
    - linux
  script:
    - mkdir build_minimal
    - cd build_minimal
    - cmake -DDEFAULT=0 -DENABLE_PARSER=1 -DENABLE_POST=1 ..
    - make -j 4
    
build_windows_msvc:
  tags:
    - windows
  script:
    - md build
    - cd build
    - cmake ..
    - msbuild package.vcxproj

variables:
  EXTRA_VERSION: "-git"

build_official_linux_gcc: &anchor_build_official_linux_gcc
  tags:
    - linux
    - official
  only:
    - master
  script:
    - mkdir build
    - cd build
    - /usr/local/bin/cmake -DGMSH_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local' -DENABLE_NATIVE_FILE_CHOOSER:bool=FALSE -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 ..
    - make package -j 2
    - /usr/local/bin/ctest -D Experimental -j 2 --output-on-failure
    - PKG=`ls gmsh-*.tar*`; scp -o StrictHostKeyChecking=no -i /home/gitlab-runner/.ssh/id_rsa ${PKG} geuzaine@gmsh.info:.wwwgmsh/beta/${PKG/\.tar\.gz/\.tgz}

tag_build_official_linux_gcc:
  variables:
    EXTRA_VERSION: ""
  <<: *anchor_build_official_linux_gcc
  only:
    - tags

build_official_windows_gcc: &anchor_build_official_windows_gcc
  tags:
    - windows
    - official
  only:
    - master
  script:
    - md build
    - cd build
    - bash -c "/usr/bin/cmake -DGMSH_EXTRA_VERSION=$EXTRA_VERSION -DCMAKE_PREFIX_PATH='/usr/local/opencascade;/usr/local;/usr/mingw32/sys-root/mingw' -DCMAKE_C_COMPILER=/usr/bin/mingw32-gcc.exe -DCMAKE_CXX_COMPILER=/usr/bin/mingw32-g++.exe -DCMAKE_Fortran_COMPILER=/usr/bin/mingw32-gfortran.exe -DCMAKE_RC_COMPILER=/usr/bin/mingw32-windres.exe -DPETSC_ARCH=complex_mumps_seq -DPETSC_DIR=/home/geuzaine/src/petsc-3.7.5 -DSLEPC_DIR=/home/geuzaine/src/slepc-3.7.3 .."
    - bash -c "/usr/bin/make package -j 2"
    - bash -c "/usr/bin/ctest -D Experimental -j 2 --output-on-failure"
    - bash -c "/usr/bin/scp -o StrictHostKeyChecking=no -i /home/geuzaine/.ssh/id_rsa gmsh-*.zip geuzaine@gmsh.info:.wwwgmsh/beta/"

tag_build_official_windows_gcc:
  variables:
    EXTRA_VERSION: ""
  <<: *anchor_build_official_windows_gcc
  only:
    - tags
